#!/bin/bash

# Hermes-Agent 日志查看快速参考
# 使用方法：./log_quick_ref.sh

echo "=========================================="
echo "Hermes-Agent 日志查看快速参考"
echo "=========================================="
echo ""

echo "📁 日志文件位置"
echo "----------------------------------------"
echo "主日志：~/.hermes/logs/agent.log"
echo "错误日志：~/.hermes/logs/errors.log"
echo "会话数据库：~/.hermes/sessions/hermes.db"
echo ""

echo "🔧 常用命令"
echo "----------------------------------------"
echo "1. 实时跟踪日志"
echo "   tail -f ~/.hermes/logs/agent.log"
echo ""
echo "2. 查看最近 50 行"
echo "   tail -n 50 ~/.hermes/logs/agent.log"
echo ""
echo "3. 使用 hermes 命令"
echo "   hermes logs"
echo "   hermes logs --follow"
echo "   hermes logs --tail 100"
echo ""
echo "4. 搜索特定内容"
echo "   grep 'pomodoro' ~/.hermes/logs/agent.log"
echo "   grep 'write_file' ~/.hermes/logs/agent.log"
echo "   grep 'File written' ~/.hermes/logs/agent.log"
echo ""
echo "5. 查看错误"
echo "   cat ~/.hermes/logs/errors.log"
echo "   tail -f ~/.hermes/logs/errors.log"
echo ""

echo "📊 使用分析工具"
echo "----------------------------------------"
echo "./hermes_log分析工具.sh stats     # 统计信息"
echo "./hermes_log分析工具.sh tools     # 工具执行"
echo "./hermes_log分析工具.sh files     # 文件操作"
echo "./hermes_log分析工具.sh watch     # 实时监控"
echo "./hermes_log分析工具.sh pomodoro  # 追踪番茄钟"
echo ""

echo "🍅 追踪番茄钟任务"
echo "----------------------------------------"
echo "1. 搜索相关日志"
echo "   grep -i 'pomodoro' ~/.hermes/logs/agent.log"
echo ""
echo "2. 查看 HTML 文件创建"
echo "   grep '\\.html' ~/.hermes/logs/agent.log"
echo ""
echo "3. 检查文件"
echo "   ls -lh pomodoro.html"
echo "   head -20 pomodoro.html"
echo ""

echo "🎯 关键日志关键词"
echo "----------------------------------------"
echo "Writing to:          # 写入文件"
echo "Reading file:        # 读取文件"
echo "File written:        # 文件写入成功"
echo "Executing tool:      # 执行工具"
echo "Tool completed:      # 工具执行完成"
echo "Calling LLM:         # 调用 LLM"
echo "LLM response:        # LLM 响应"
echo "Session created:     # 会话创建"
echo "Session saved:       # 会话保存"
echo ""

echo "⚙️ 配置日志级别"
echo "----------------------------------------"
echo "查看当前级别"
echo "  grep 'level:' ~/.hermes/config.yaml"
echo ""
echo "设置为 DEBUG"
echo "  hermes config set logging.level DEBUG"
echo ""
echo "或编辑配置文件"
echo "  nano ~/.hermes/config.yaml"
echo "  找到 logging.level 改为 DEBUG"
echo ""

echo "🔍 问题排查"
echo "----------------------------------------"
echo "文件没创建？"
echo "  grep 'ERROR' ~/.hermes/logs/errors.log"
echo "  grep 'write_file' ~/.hermes/logs/agent.log"
echo ""
echo "工具调用失败？"
echo "  grep 'Tool.*failed' ~/.hermes/logs/errors.log"
echo ""
echo "API 调用失败？"
echo "  grep 'API.*error' ~/.hermes/logs/errors.log"
echo ""

echo "=========================================="
echo "更多详情查看文档："
echo "  - 如何通过日志查看 Hermes-Agent 运行逻辑.md"
echo "  - 番茄钟任务日志分析实战.md"
echo "=========================================="
